import Head from "next/head"
import { Inter } from "@next/font/google"
import styles from "@/styles/Home.module.css"
import { getProductsById } from "@/services/getProductById"
import { Layout } from "@/containers/Layout"


export default function Home() {
	getProductsById({id:6}).then(response => console.log(response))
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="preconnect" href="https://fonts.googleapis.com"/>
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet"></link>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout />
		</>
	)
}
